Us 11 coversbydiet
lelionvert/socrates-team2 pull request #34
Opened 2017-08-31 15:38 UTC by bassail

Hello everyone , good luck have fun

2017-09-01 09:20 UTC, udebella requested changes

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/attendee/ConfirmationService.java
> +    void addDiet(String candidateEmail, Diet diet);
Services should consume domain object, so we should probably use Email type here

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/attendee/ConfirmationServiceImpl.java
>          final List<Candidate> attendeesList = new ArrayList<>();
you could rename those variables to get rid of type (`attendeesList` => `attendees`)

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/attendee/ConfirmationServiceImpl.java
> +        for (Confirmation confirmation : confirmationsList) {
You can use stream api for that.

The best would be to give a list of candidateId to findByCandidateID to make only one request to the database

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/attendee/ConfirmationServiceImpl.java
> +        final Candidate candidate = foundCandidate.get();
If the candidate does not exist it throws an exception here. So that line should be droped. And you should use the foundCandidate.ifPresent which is behind.

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/candidate/Candidate.java
> +        public CandidateBuilder() {
That builder should stay private

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/candidate/Candidate.java
> +        public CandidateBuilder fromCandidate(Candidate candidate) {
and this method should be static I guess

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/candidate/CandidateRepository.java
> +    void updateDietOf(CandidateId candidateId, Diet diet);
That method should be in a DietRepository as for confirmations

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/checkin/CheckIn.java
> +    public boolean isPresentAt(LocalDateTime dateTime){
`CheckIn.isPresentAt(time)` sound weird
I would rather say `CheckIn.wasBefore(time)`, no?

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/attendee/ConfirmationService.java
> +    void addDiet(String candidateEmail, Diet diet);
You could alse give it a candidateId

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/checkin/CheckInServiceImpl.java
> +        return foundCheckIn.map(checkIn -> checkIn.isPresentAt(dateTime)).orElse(false);
that's an odd implementation, but I don't really know how to improve that...

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/Catering.java
> +        return this.coversByDietByDay.get(new DietOrder(mealTime, diet));
`coversByDietByDay` == `coversByDietAndDay` ?

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/Catering.java
> +    public Quantity numberOfCover(MealTime mealTime, Diet diet) {
you could give it a DietOrder directly, no?

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/MealService.java
> +    @Deprecated
I think you forgot to remove that method ;)

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/MealServiceImpl.java
> +    public Map<MealTime, Map<Diet, Long>> getCoversByDiet() {
So implem too should have been removed

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/MealServiceImpl.java
> +    public Catering generateOrder() {
That method is too long, it should be break into pieces (does not fit in my screen :p)

2017-09-01 09:20 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/MealServiceImpl.java
> +            for (MealTime mealTime : mealTimes) {
You could extract method on that for example

2017-09-01 09:20 UTC, udebella commented on src/test/java/fr/socrates/domain/attendee/ConfirmationServiceImplTest.java
> +    @Test
Reformating failure?

2017-09-01 09:20 UTC, udebella commented on src/test/java/fr/socrates/domain/attendee/ConfirmationServiceImplTest.java
> +    public void should_add_a_vegan_diet_for_a_given_participant() throws Exception {
It's not an unit test cause you depend on adding a candidate and confirming the candidate. It's an acceptance test...

2017-09-01 09:20 UTC, udebella commented on src/test/java/fr/socrates/domain/meal/MealCateringFeature.java
> +    private Printer console;
@Deprecated cause we should not keep that

2017-09-01 09:20 UTC, udebella commented on src/test/java/fr/socrates/domain/meal/MealCateringFeature.java
> +    public void setUp() throws Exception {
we could extract methods : we initialize candidates, checkins and we confirm candidates

2017-09-01 09:20 UTC, udebella commented on src/test/java/fr/socrates/domain/meal/MealCateringFeature.java
> +    private static final String JOHN_DOE_FR = "john@doe.fr";
We can use an enum?

2017-09-01 09:20 UTC, udebella commented on src/test/java/fr/socrates/domain/meal/MealCateringFeature.java
> +        assertThat(cateringOrdering.numberOfCover(MealTime.THURSDAY_NIGHT, VEGAN)).isEqualTo(Quantity.of(2));
I think we could collapse those into one assert

2017-09-01 10:26 UTC, bassail commented on src/main/java/fr/socrates/domain/attendee/ConfirmationService.java
> +    void addDiet(String candidateEmail, Diet diet);
Done

2017-09-05 08:23 UTC, bassail commented on src/main/java/fr/socrates/domain/checkin/CheckIn.java
> +    public boolean isPresentAt(LocalDateTime dateTime){
No

2017-09-05 08:23 UTC, bassail commented on src/main/java/fr/socrates/domain/checkin/CheckInServiceImpl.java
> +        return foundCheckIn.map(checkIn -> checkIn.isPresentAt(dateTime)).orElse(false);
Thanks, that's really useful

2017-09-05 08:24 UTC, bassail commented on src/main/java/fr/socrates/domain/meal/Catering.java
> +    public Quantity numberOfCover(MealTime mealTime, Diet diet) {
No

2017-09-05 08:31 UTC, bassail commented on src/main/java/fr/socrates/domain/meal/Catering.java
> +        return this.coversByDietByDay.get(new DietOrder(mealTime, diet));
https://media.giphy.com/media/C6JQPEUsZUyVq/giphy.gif

2017-09-05 08:32 UTC, bassail commented on src/main/java/fr/socrates/domain/meal/MealService.java
> +    @Deprecated
https://media.giphy.com/media/3oEjHKvjqt5pssL99C/giphy.gif

2017-09-05 08:36 UTC, bassail commented on src/main/java/fr/socrates/domain/meal/MealServiceImpl.java
> +    public Catering generateOrder() {
https://www.youtube.com/watch?v=ROF4uNjrB4U

2017-09-05 10:17 UTC, udebella commented on src/main/java/fr/socrates/domain/candidate/CandidateRepository.java
> +    void updateDietOf(CandidateId candidateId, Diet diet);
No repository added for that iteration

2017-09-05 10:19 UTC, udebella commented on src/main/java/fr/socrates/domain/checkin/CheckInServiceImpl.java
> +        return foundCheckIn.map(checkIn -> checkIn.isPresentAt(dateTime)).orElse(false);
Leave it like that for now

2017-09-05 10:22 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/MealServiceImpl.java
> +            for (MealTime mealTime : mealTimes) {
Leave it like that for now

2017-09-05 10:23 UTC, udebella commented on src/test/java/fr/socrates/domain/meal/MealCateringFeature.java
> +        assertThat(cateringOrdering.numberOfCover(MealTime.THURSDAY_NIGHT, VEGAN)).isEqualTo(Quantity.of(2));
Leave it like that for now

2017-09-05 10:30 UTC, udebella commented on src/main/java/fr/socrates/domain/meal/Catering.java
> +    public Quantity numberOfCover(MealTime mealTime, Diet diet) {
Depends on how we call that

2017-09-05 10:30 UTC, udebella approved these changes

2017-09-05 10:31 UTC, merged